# Generated by Django 3.0.3 on 2020-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='userid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
